apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "apps.openshift.io/v1alpha1",
          "kind": "ServiceBindingRequest",
          "metadata": {
            "name": "example-servicebindingrequest"
          },
          "spec": {
            "applicationSelector": {
              "group": "apps",
              "resource": "deployments",
              "resourceRef": "nodejs-rest-http-crud",
              "version": "v1"
            },
            "backingServiceSelector": {
              "group": "postgresql.example.dev",
              "kind": "Database",
              "resourceRef": "pg-instance",
              "version": "v1alpha1"
            },
            "mountPathPrefix": "/var/credentials"
          }
        }
      ]
    capabilities: Basic Install
  name: service-binding-operator.v0.1.1-256
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ServiceBindingRequest expresses intent to bind an operator-backed
        service with an application workload.
      displayName: Service Binding Request
      kind: ServiceBindingRequest
      name: servicebindingrequests.apps.openshift.io
      version: v1alpha1
  description: Placeholder description
  displayName: Service Binding Operator
  install:
    spec:
      deployments:
      - name: service-binding-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: service-binding-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: service-binding-operator
            spec:
              containers:
              - command:
                - service-binding-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: service-binding-operator
                image: quay.io/redhat-developer/app-binding-operator:58ea511
                imagePullPolicy: Always
                name: service-binding-operator
                resources: {}
              serviceAccountName: service-binding-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - service-binding-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - apps.openshift.io
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - '*'
          resources:
          - '*'
          verbs:
          - get
          - list
          - watch
          - update
        - apiGroups:
          - serving.knative.dev
          resources:
          - services
          verbs:
          - '*'
        serviceAccountName: service-binding-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider: {}
  version: 0.1.1-256
